export const LOGIN_MUTATION_KEY = "LOGIN_MUTATION_KEY";
export const REGISTER_MUTATION_KEY = "REGISTER_MUTATION_KEY";
export const LOGOUT_MUTATION_KEY = "LOGOUT_MUTATION_KEY";
export const GET_ME_KEY = "GET_ME_KEY";

// authors
export const CREATE_AUTHOR_MUTATION_KEY = "CREATE_AUTHOR_MUTATION_KEY";
export const AUTHOR_LIST = "AUTHOR_LIST";

// categories
export const CREATE_CATEGORY_MUTATION_KEY = "CREATE_CATEGORY_MUTATION_KEY";
export const CATEGORIES = "CATEGORIES";

// courses
export const CREATE_COURSE_MUTATION_KEY = "CREATE_COURSE_MUTATION_KEY";
export const COURSE_LIST = "COURSE_LIST";
export const COURSE = "COURSE";