export const LOGIN_MUTATION_KEY = "LOGIN_MUTATION_KEY";
export const REGISTER_MUTATION_KEY = "REGISTER_MUTATION_KEY";
export const LOGOUT_MUTATION_KEY = "LOGOUT_MUTATION_KEY";
export const GET_ME_KEY = "GET_ME_KEY";

// authors
export const CREATE_AUTHOR_MUTATION_KEY = "CREATE_AUTHOR_MUTATION_KEY";
export const AUTHOR_LIST = "AUTHOR_LIST";
export const UPDATE_AUTHOR_MUTATION_KEY = "UPDATE_AUTHOR_MUTATION_KEY";
export const DELETE_AUTHOR_MUTATION_KEY = "DELETE_AUTHOR_MUTATION_KEY";
export const ARCHIVE_AUTHOR_MUTATION_KEY = "ARCHIVE_AUTHOR_MUTATION_KEY";
export const GET_AUTHORS_COUNT = "GET_AUTHORS_COUNT";

// categories
export const CREATE_CATEGORY_MUTATION_KEY = "CREATE_CATEGORY_MUTATION_KEY";
export const CATEGORIES = "CATEGORIES";
export const DELETE_CATEGORIES_MUTATION_KEY = "DELETE_CATEGORIES_MUTATION_KEY";
export const ARCHIVE_CATEGORIES_MUTATION_KEY =
  "ARCHIVE_CATEGORIES_MUTATION_KEY";
export const UPDATE_CATEGORY_MUTATION_KEY = "UPDATE_CATEGORY_MUTATION_KEY";

// courses
export const CREATE_COURSE_MUTATION_KEY = "CREATE_COURSE_MUTATION_KEY";
export const COURSE_LIST = "COURSE_LIST";
export const COURSE = "COURSE";
export const UPDATE_COURSE_MUTATION_KEY = "UPDATE_COURSE_MUTATION_KEY";
export const DELETE_COURSE_MUTATION_KEY = "DELETE_COURSE_MUTATION_KEY";
export const ARCHIVE_COURSE_MUTATION_KEY = "ARCHIVE_COURSE_MUTATION_KEY";

// videos
export const CREATE_VIDEO_MUTATION_KEY = "CREATE_VIDEO_MUTATION_KEY";
export const UPDATE_VIDEO_MUTATION_KEY = "UPDATE_VIDEO_MUTATION_KEY";
export const COURSE_VIDEOS = "COURSE_VIDEOS";
export const DELETE_VIDEO_MUTATION_KEY = "DELETE_VIDEO_MUTATION_KEY";
export const ARCHIVE_VIDEO_MUTATION_KEY = "ARCHIVVIDEO_MUTATION_KEY";

// users
export const GET_USERS_COUNT = "GET_USERS_COUNT";
export const GET_USERS = "GET_USERS";
